Layout/ClassStructure:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/LineLength:
  Max: 100
  # To make it possible to copy or click on URIs in the code, we allow lines
  # containing a URI to be longer than Max.
  AllowURI: true
  URISchemes:
    - http
    - https

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: false

Lint/DeprecatedOpenSSLConstant:
  Enabled: false

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/DuplicateRescueException:
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: true

Lint/FloatComparison:
  Enabled: true

Lint/MissingSuper:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/OutOfRangeRegexpRef:
  Enabled: true

Lint/RaiseException:
  Enabled: false

Lint/SelfAssignment:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/TopLevelReturnWithArgument:
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

Metrics/AbcSize:
  # The ABC size is a calculated magnitude, so this number can be an Integer or
  # a Float.
  Max: 15

Metrics/BlockLength:
  CountComments: false
  Max: 25

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  CountComments: false
  Max: 200

# Avoid complex methods.
Metrics/CyclomaticComplexity:
  Max: 6

Metrics/MethodLength:
  CountComments: false
  Max: 24

Metrics/ModuleLength:
  CountComments: false
  Max: 200

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: true

Metrics/PerceivedComplexity:
  Max: 12

Rails:
  Enabled: true

Rails/Delegate:
  Enabled: true

Rails/FilePath:
  Enabled: false

Rails/SaveBang:
  Enabled: true

Style/AccessorGrouping:
  Enabled: true
  EnforcedStyle: grouped

Style/ArrayCoercion:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/CaseLikeIf:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/ExplicitBlockArgument:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true
  EnforcedStyle: scientific

Style/GlobalStdStream:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashLikeCase:
  Enabled: true 
  MinBranchesCount: 4

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: false

Style/RedundantFileExtensionInRequire:
  Enabled: false

Style/RedundantRegexpCharacterClass:
  Enabled: false

Style/RedundantRegexpEscape:
  Enabled: true

Style/ReturnNil:
  Enabled: true

Style/SingleArgumentDig:
  Enabled: true

Style/SlicingWithRange:
  Enabled: false

Style/StringConcatenation:
  Enabled: false
